### ISSUE TITLE
Selecting text causes crash

### ISSUE THREAD

**Issue by Relequestual** [akrabat/SublimeFunctionNameDisplay#19]
When selecting text in ST2 with this package enabled, ST2 crashes. Have to force quit. Build 2217 on osx 10.8.3
Get the Apple crash dump, but no idea what to look for =/ sorry. Can email it to you directly if you think it might help.

**Comment by akrabat** [comment]
I no longer use, ST2. Happy to accept a pull request that fixes this issue though.
