### ISSUE TITLE
I installed the plugin on ST3 and saw no changes

### ISSUE THREAD

**Issue by PerfectCarl** [akrabat/SublimeFunctionNameDisplay#21]
Hello I installed your plugin on ST3 (unregistred) and tried it on Js files (and [vala files](http://www.wikiwand.com/en/Vala_%28programming_language%29) - think C#) and didn't see anything new displayed in the titlebar (just the regular file path).

Do you have any screenshot of the expected results? 
Or a list of languages that are expected to work?

**Comment by akrabat** [comment]
It looks like this: http://i.19ft.com/78f2c343.png - you can see "about" in the status bar.

It uses the scope information to work out the name. Specifically it looks for [`meta.function`](https://github.com/akrabat/SublimeFunctionNameDisplay/blob/master/FunctionNameStatus.py#L92) for the function name and [`entity.name.type.class`](https://github.com/akrabat/SublimeFunctionNameDisplay/blob/master/FunctionNameStatus.py#L92) for the class name.
