### ISSUE TITLE
wrong function name 

### ISSUE THREAD

**Issue by anandsunku** [akrabat/SublimeFunctionNameDisplay#22]
I love your plugin fantastic, i slowly come out from microsoft visual studio, 

Unfortunately just after below code, function name is always displayed as Parse.

hope fixing this will make the plugin more robust. 

LONG
Parse(
    __in int argc,
    __in_ecount(argc) char *argv[]
    )
/*++
Routine Description:

    Called by main() to parse command line parms

Arguments:

    argc and argv that was passed to main()

Return Value:

    Sets global flags as per user function request

--*/
{
    int i;
    BOOL ok;
    LONG error = ERROR_SUCCESS;

    for (i=0; i<argc; i++) {
        if (argv[i][0] == '-' ||
            argv[i][0] == '/') {
            switch(argv[i][1]) {
            case 'V':
            case 'v':
                if (( (i+1 < argc ) &&
                      ( argv[i+1][0] != '-' && argv[i+1][0] != '/'))) {
                    //
                    // use version in commandline
                    //
                    i++;
                    ok = ValidateCoinstallerVersion(argv[i]);
                    if (!ok) {
                        printf("Not a valid format for coinstaller version\n"
                               "It should be characters between A-Z, a-z , 0-9\n"
                               "The version format is MMmmm where MM -- major #, mmm - serial#");
                        error = ERROR_INVALID_PARAMETER;
                        break;
                    }
                    if (FAILED( StringCchCopy(G_coInstallerVersion,
                                              MAX_VERSION_SIZE,
                                              argv[i]) )) {
                        break;
                    }
                    G_versionSpecified = TRUE;

                }
                else{
                    printf(USAGE);
                    error = ERROR_INVALID_PARAMETER;
                }
                break;
            case 'l':
            case 'L':
                G_fLoop = TRUE;
                break;
            default:
                printf(USAGE);
                error = ERROR_INVALID_PARAMETER;

            }
        }
    }
    return error;
}

**Comment by akrabat** [comment]
Are you able to format this into a pull request?

**Comment by akrabat** [comment]
I've looked into this and I don't think that there's anything I can do about it.

The plugin uses SublimeText's scope system to find the closest `meta.function` that above the current line and assumes that we're in that function. There isn't a scope for "function has finished", so we can't detect when we leave the function. 

If anyone has an idea on how to do this, then I'm all ears!
